# The NUMPY.RANDOM package

# About this project:

In this project, we will talk about the Numpy.random package. It will explain the use of this package, covering the following points:
1. Explain the overall purpose of the package. 
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions. 
4. Explain the use of seeds in generating pseudorandom numbers.


### What is NumPy?
**NumPy** is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## 1. Overall purpose of the package:

The NUMPY.RANDOM PACKAGE is one of the function for doing random sampling in numpy, a suite of functions based on pseudorandom number generation. It returns an array of specified shape and fills it with random floats in the half-open interval.

RANDOM means something that cannot be predicted logically.

**Numpy** has several advantages over Python lists, such as:
- **Memory Usage**: NumPy arrays are fixed-length arrays, while python has lists that are extensible;
- **Speed**: NumPy uses under-the-hood optimizations such as transposing and chunked multiplications; the operations are vectorized so that the looped operations are performed much faster
- **Filtering**: A pretty handy trick that can be used to separate data based on some condition or the label, which is very useful in data analytics and machine learning. Source: [Advantages of using NumPy over Python Lists](https://medium.com/swlh/why-use-numpy-d06c573fbcda)

In [2]:
# Importing NUMPY library:
import numpy as np

### 1.1: Array Types

There are 2 types of array: **SINGLE DIMENSIONAL** and **MULTI DIMENSIONAL**

**SINGLE DIMENSIONAL:**

In [3]:
single_array = np.array([1, 2, 3, 4])
print(single_array)

[1 2 3 4]


**MULTI DIMENSIONAL:**

In [6]:
multi_array = np.array([(1, 2, 3, 4), (2, 4, 6, 8), (3, 6, 9, 12)])
print(multi_array)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


## 2. Simple random data and Permutations functions

### 2.1: Simple Random data
Simple Random Sampling is a technique in which every item in the population has an equal possibility of being selected within the totality of the sample. This completely depends on goes the concepts of probability and therefore known as the method of chances.

Some of advantages of using Simple Random:
- Reduces bias against other sampling methods 
- Pick smaller sample size from the original
- No size restrictions for sample results

In order to use it, we will need to import the random funcion:

In [12]:
# Importing random function
import random as rd

*Testing the `random.sample()` function:*

In [33]:
#sorting 3 random numbers for a list:
list = 1, 2, 5, 9, 10, 13, 14
print("The 3 sorted numbers are: ",rd.sample(list, 3)) 
print("")

#simulating lottery numbers sorting (creating list with "arange" function):
list1 = np.arange(1, 61).tolist()
print("The lottery result is:",rd.sample(list1,6))

The 3 sorted numbers are:  [13, 5, 9]

The lottery result is: [24, 50, 43, 59, 32, 49]
