# The NUMPY.RANDOM package

# About this project:

In this project, we will talk about the Numpy.random package. It will explain the use of this package, covering the following points:
1. Explain the overall purpose of the package. 
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions. 
4. Explain the use of seeds in generating pseudorandom numbers.


### What is NumPy?
**NumPy** is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## 1. Overall purpose of the package:

The NUMPY.RANDOM PACKAGE is one of the function for doing random sampling in numpy, a suite of functions based on pseudorandom number generation. It returns an array of specified shape and fills it with random floats in the half-open interval.

RANDOM means something that cannot be predicted logically.

**Numpy** has several advantages over Python lists, such as:
- **Memory Usage**: NumPy arrays are fixed-length arrays, while python has lists that are extensible;
- **Speed**: NumPy uses under-the-hood optimizations such as transposing and chunked multiplications; the operations are vectorized so that the looped operations are performed much faster
- **Filtering**: A pretty handy trick that can be used to separate data based on some condition or the label, which is very useful in data analytics and machine learning. Source: [Advantages of using NumPy over Python Lists](https://medium.com/swlh/why-use-numpy-d06c573fbcda)

In [4]:
# Importing NUMPY library:
import numpy as np

### 1.1: Array Types

There are 2 types of array: **SINGLE DIMENSIONAL** and **MULTI DIMENSIONAL**

**SINGLE DIMENSIONAL:**

In [3]:
single_array = np.array([1, 2, 3, 4])
print(single_array)

[1 2 3 4]


**MULTI DIMENSIONAL:**

In [6]:
multi_array = np.array([(1, 2, 3, 4), (2, 4, 6, 8), (3, 6, 9, 12)])
print(multi_array)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


## 2. Simple random data and Permutations functions

### 2.1: Simple Random data
Simple Random Sampling is a technique in which every item in the population has an equal possibility of being selected within the totality of the sample. This completely depends on goes the concepts of probability and therefore known as the method of chances.

Some of advantages of using Simple Random:
- Reduces bias against other sampling methods 
- Pick smaller sample size from the original
- No size restrictions for sample results

In order to use it, we will need to import the random funcion:

In [2]:
# Importing random function
import random as rd

#### Testing the `random.sample()` function:
This function is used to select multiple items from a list without repeating

In [15]:
#sorting 3 random numbers for a list:
list = 1, 2, 5, 9, 10, 13, 14
print("The 3 sorted numbers are: ",rd.sample(list, 3)) 
print("")

#simulating lottery numbers sorting (creating list with "arange" function):
list1 = np.arange(1, 61).tolist()
print("The lottery result is:",rd.sample(list1,6))
print("")

#sorting 3 names from a list
names = ["Peter", "Mary", "James", "Suzan", "Thomasz", "Aoife", "Aoine"]
samplelist3 = rd.sample(names, k=3)
print("The 3 sorted names are: ",samplelist3)

The 3 sorted numbers are:  [10, 5, 1]

The lottery result is: [23, 60, 21, 45, 47, 2]

The 3 sorted names are:  ['Aoine', 'James', 'Suzan']


#### Testing the random.choice() function:
This function returns a random element from a non-empty sequence. It can be used to select a random item from the available data within the list

In [57]:
# Choosing a random item from a list:

itemlist=['watermelon', 'pineapple', 'orange', 'apple', 'banana']
print("The chosen fruit is", rd.choice(itemlist))

The chosen fruit is pineapple


#### Testing the random.randint() function:
This function returns a random integer within a range. Only integer values are accepted in this function. Other values other than integer will raise a `ValueError: non-integer arg 1` error

In [60]:
randomNum1 = rd.randint(0,50)
print("Random integer:", randomNum1)

randomNum2 = rd.randint(150,500)
print("Random integer:", randomNum2)


Random integer: 31
Random integer: 211


### 2.2: Permutations functions

In mathematics, a permutation of a set is, loosely speaking, an arrangement of its members into a sequence or linear order, or if the set is already ordered, a rearrangement of its elements. The word "permutation" also refers to the act or process of changing the linear order of an ordered set. Source: [Wikipedia - Permutation](https://en.wikipedia.org/wiki/Permutation)

#### Permutation:

In [33]:
# Importing library permutations
from itertools import permutations as pmt

# Generation permutation for string [A, B, C]

values = ['A', 'B', 'C']
permut = pmt(values)
for i in permut:
    print(*i)

A B C
A C B
B A C
B C A
C A B
C B A


**Permutation with certain number of elements**


In [39]:
values = ['A', 'B', 'C']
permut = pmt(values, 2)
for i in permut:
    print(*i)

A B
A C
B A
B C
C A
C B


**Shuffle:**

In [49]:
# Testing the shuffle functions

number_list = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
print("Original number list:", number_list)

rd.shuffle(number_list)
print("Shuffled number list:", number_list)
print("")

characters_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print("Original character list", characters_list)

rd.shuffle(characters_list)
print("Shuffled characters list:", characters_list)

Original number list: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
Shuffled number list: [2, 31, 29, 3, 5, 11, 13, 19, 37, 17, 23, 7]

Original character list ['a', 'b', 'c', 'd', 'e', 'f', 'g']
Shuffled characters list: ['f', 'd', 'g', 'e', 'b', 'a', 'c']


## 3. Explain the use and purpose of at least five “Distributions” functions.